export const itemArray = [
    {
      id: Math.random(), 
      title :"Moon Lovers",
      posterUrl: `https://asianwiki.com/images/a/ab/Moon_Lovers.p1.jpg`,
      description: "Hae-Soo (IU) travels back in time to the Goryeo era. There, she falls in love with Wang So (Lee Joon-Gi) who makes other people tremble with fear.",
      rate: "5",
    },
    {  
        id: Math.random(),
        title :"Healer",
        posterUrl: `https://asianwiki.com/images/1/12/Healer-p1.jpg`,
        description: "Kim Moon-Ho (Yoo Ji-Tae) is a popular reporter at major broadcasting company. One day, he learns the truth of a case that took place in the past. He intentionally approaches people who are related to the case...",
        rate: "4",
      },
    {  
      id: Math.random(),
      title :"King 2 hearts",
      posterUrl: `https://occ-0-300-299.1.nflxso.net/art/85cae/0a50fa4dfee1f06a4ffa0f38bfc672b8ac585cae.jpg`,
      description: "Prince Jae-Ha (Lee Seung-Gi) from South Korea and North Korean Special Force instructor Kim Hang-Ah (Ha Ji-Won) who become husband & wife through an arranged marriage.",
      rate: "5",
    },
    {   
        id: Math.random(),
        title :"49 Days",
        posterUrl: `https://asianwiki.com/images/6/66/49days-p1.jpg`,
        description: "Ji Hyeon is a young woman leading an ideal life. She has a tragic traffic accident.An angel of death decides to give her a second chance at life on the condition that in 49 days she will have to find three people except those of her family who are crying purely for her.",
        rate: "4",
    },
    {
        id: Math.random(),
        title :"Descendants of the Sun",
        posterUrl: `https://asianwiki.com/images/e/e3/Descendants_of_the_Sun-p1.jpg`,
        description: "Shi-Jin (Song Joong-Ki) is the captain of the special forces and Mo-Yeon (Song Hye-Kyo) is a doctor they fall in love and begin to date, but due to their jobs their dates don't go well.Eight months later,she lead a medical team in Uruk. There, they meet again.",
        rate: "4",
    },
    {
        id: Math.random(),
        title :"Itaewon Class",
        posterUrl: `https://asianwiki.com/images/c/c8/Itaewon_Class-mp1.jpg`,
        description: "Park Sae-Ro-Yi's father dies in a motorcycle accident caused by Jang Geun-Won.Park Sae-Ro-Yi viciously defeats Jang Geun-Won. He was soon arrested and sentenced to prison for the violent assault. Park Sae-Ro-Yi decides to get revenge.",
        rate: "3",
    },
    {
        id: Math.random(),
        title :"Uncontrollably Fond",
        posterUrl: `https://channel-korea.com/wp-content/uploads/2019/04/filmafisi.jpg`,
        description: "Shin Joon Young (Kim Woo Bin) and No Eul (Suzy) were romantically involved in their youth. Joon Young is now ultra famous while No Eul has become a producer. When their paths cross again years later, Joon Young realizes that No Eul has become a very different person than he remembered ...",
        rate: "3",
    },
    {
        id: Math.random(),
        title :"City Hunter",
        posterUrl: `https://asianwiki.com/images/b/b5/City_HunterC-p2.jpg`,
        description: "Lee Jin-Pyo (Kim Sang-Joong) and Park Moo-Yul (Park Sang-Min) worked as bodyguards at the South Korean president's home, the Blue House. But Lee Jin-Pyo wants revenge for his father who was killed by his own government...",
        rate: "4",
    },
    {
        id: Math.random(),
        title :"Radiant Office",
        posterUrl: `https://asianwiki.com/images/3/3c/Radiant_Office-p2.jpg`,
        description: "A woman keeps failing to find a job. She decides to jump into the Han River to decide. But she is rescued and sent to the hospital emergency room. There, she hears that she may have a a fatal disease and that she may not have much time to live...",
        rate: "5",
    },
    {
        id: Math.random(),
        title :"Pinocchio",
        posterUrl: `https://scontent.ftun11-1.fna.fbcdn.net/v/t1.0-9/37180593_684642728538667_6564905538260303872_n.jpg?_nc_cat=104&ccb=2&_nc_sid=0debeb&_nc_ohc=l04INk2cXToAX-PLZor&_nc_ht=scontent.ftun11-1.fna&oh=f82712b7572511979d22e3923319e159&oe=5FBFB565`,
        description: "Choi In-Ha and Choi Dal-Po have known each other since their childhood, when Dal-Po was adopted by In-Ha’s grandfather, and they both decide to take up journalism for personal reasons. But Choi In-Ha suffers from Pinocchio syndrome and Choi Dal-Po has a deep hatred for the media, which are the cause of the loss of his biological family ...", 
        rate: "4",
    },
    {
        id: Math.random(),
        title :"Faith",
        posterUrl: `https://asianwiki.com/images/f/f0/The_Great_Doctor_-_Korean_Drama-p1.jpg`,
        description: "Faith depicts the love between a warrior from the Goryeo Period and a female doctor from the present day, their love transcending time and space..",
        rate: "4",
    },
    {
        id: Math.random(),
        title :"The K2",
        posterUrl: `https://i.pinimg.com/originals/79/f6/3b/79f63bdcb9328449f3535a5398583e22.jpg`,
        description: "Kim Je-Ha (Ji Chang-Wook) is former solider for hire. He is also called K2. He is hired as a bodyguard by Choi Yoo-Jin (Song Yoon-A). Choi Yoo-Jin is the wife of a presidential candidate (Cho Seong-Ha) and the daughter from a chaebol family. Meanwhile, Ko An-Na (Yoona) is the secret daughter of the presidential hopeful. She is also a recluse.",
        rate: "5",
    },
  ];
  